{"name": "[TiTile]case 登录失败逆向场景", "status": "passed", "parameters": [{"name": "case", "value": "{'user': '', 'passwd': '254992', 'check': '请输入手机号'}"}], "start": 1636516800132, "stop": 1636516801104, "uuid": "fa3829b7-58bd-4843-92b6-5f064cfc2170", "historyId": "f0bfd36e151bd6809e3bea92a4f95e89", "testCaseId": "98e067a681f547a2e44e78c948720b9e", "fullName": "TestCases.test_login.TestLogin#test_login_failed_invalid_data", "labels": [{"name": "epic", "value": "[epic]盛杰运营后台"}, {"name": "story", "value": "[Story]用户根据用户名密码登录系统"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-OTOI92D"}, {"name": "thread", "value": "14180-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}