{"name": "test_login_failed_invalid_data[case2]", "status": "passed", "parameters": [{"name": "case", "value": "{'user': '', 'passwd': '', 'check': '请输入手机号'}"}], "start": 1636516728189, "stop": 1636516729142, "uuid": "bebf6c2a-6ff6-496d-9d13-2eece9f95456", "historyId": "e60344e31024accddf6073cc86c6051a", "testCaseId": "98e067a681f547a2e44e78c948720b9e", "fullName": "TestCases.test_login.TestLogin#test_login_failed_invalid_data", "labels": [{"name": "epic", "value": "[epic]盛杰运营后台"}, {"name": "story", "value": "[Story]用户根据用户名密码登录系统"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-OTOI92D"}, {"name": "thread", "value": "17268-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}