{"name": "test_login_failed_invalid_data[case2]", "status": "passed", "parameters": [{"name": "case", "value": "{'user': '', 'passwd': '', 'check': '请输入手机号'}"}], "start": 1636516638125, "stop": 1636516639121, "uuid": "90da76c3-c09b-4d80-b963-5e7095e61837", "historyId": "e60344e31024accddf6073cc86c6051a", "testCaseId": "98e067a681f547a2e44e78c948720b9e", "fullName": "TestCases.test_login.TestLogin#test_login_failed_invalid_data", "labels": [{"name": "epic", "value": "[epic]盛杰运营后台"}, {"name": "tag", "value": "@pytest.mark.usefixtures('refresh')"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-OTOI92D"}, {"name": "thread", "value": "9592-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login"}]}